name: "BE Slack Notify Action"
description: "Let everyone know of your shananigans"
author: "Binaryedge.io"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "aperture"
  color: "orange"
